apiVersion: v1
kind: PersistentVolume
metadata:
  
  labels:
    app: airflow-webserver-pv0
  name: airflow-webserver-pv0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1000Mi
  hostPath:
    path: "/workspaces/airflow-spark-kuber/dags"
status: {}

---
