apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  
  labels:
    app: airflow-webserver-claim0
  name: airflow-webserver-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: airflow-webserver-pv0  # Name of the corresponding PV
status: {}
