apiVersion: v1
kind: Service
metadata:

  labels:
    app: jupyter-spark
  name: jupyter-spark
spec:
  type: NodePort
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
      nodePort: 32002
  selector:
    app: jupyter-spark
status:
  loadBalancer: {}
