apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  
  labels:
    app: jupyter-spark-claim2
  name: jupyter-spark-claim2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
