apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  
  labels:
    app: spark-claim1
  name: spark-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: spark-pv1
status: {}
