apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  
  labels:
    app: spark-claim0
  name: spark-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: spark-pv0
status: {}
