apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    app: spark-worker-1
  name: spark-worker-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spark-worker-1
  strategy:
    type: Recreate
  template:
    metadata:

      
      labels:
        app: spark-worker-1
    spec:
      containers:
        - env:
            - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_MASTER_URL
              value: spark://spark:7077
            - name: SPARK_MODE
              value: worker
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              value: "no"
            - name: SPARK_RPC_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_SSL_ENABLED
              value: "no"
            - name: SPARK_WORKER_CORES
              value: "1"
            - name: SPARK_WORKER_MEMORY
              value: 1G
          image: bitnami/spark:3.1.2
          name: spark-worker-1
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/spark/app
              name: spark-claim0
            - mountPath: /usr/local/spark/resources
              name: spark-claim1
      restartPolicy: Always
      volumes:
        - name: spark-claim0
       #   persistentVolumeClaim:
        #    claimName: spark-claim0
        - name: spark-claim1
        #  persistentVolumeClaim:
          #  claimName: spark-claim1
status: {}
