apiVersion: v1
kind: PersistentVolume
metadata:
  
  labels:
    app: spark-pv0
  name: spark-pv0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  hostPath:
    path: "/workspaces/airflow-spark-kuber/spark"
status: {}

---
