apiVersion: v1
kind: Service
metadata:

  labels:
    app: spark
  name: spark
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 32000
    - name: "7077"
      port: 7077
      targetPort: 7077
      nodePort: 32001
  selector:
    app: spark
status:
  loadBalancer: {}
